### ISSUE TITLE
你好，我想问一下使用hyprland的话，代理是如何设置的

### ISSUE THREAD

**Issue by ogios** [day0xy/hyprland-config#1]
我使用的是clash, 即便开tun或者service mode都无法令全局应用都走代理，但也没找到系统设置之类的地方设置代理

有的应用可以在里面配置代理还好，有的不行就比较难受，我现在使用的是firefox，还有个问题就是websocket连接无法被代理上，例如discord的，总是连接失败

想问一下你是怎么配置的

**Comment by day0xy** [comment]
@ogios 我用的是v2raya,全局透明代理。  这个感觉比clash方便，web端配置

**Comment by ogios** [comment]
> @ogios 我用的是v2raya,全局透明代理。 这个感觉比clash方便，web端配置

感谢，配好了
